CORE/urls.py
from django.urls import path
from . import views

app_name = "CORE"
urlpatterns = [
    path('CustomerCreationWizard/', views.CustomerCreationWizard.as_view(), name='CustomerCreationWizard'),
    path('EmployeeCreationWizard/', views.EmployeeCreationWizard.as_view(), name='EmployeeCreationWizard'),
    
    path('spare_part_create', views.spare_part_create, name='spare_part_create'),
    path('inventory_invoice_create', views.inventory_invoice_create, name='inventory_invoice_create'),

    path('vehicle_create/', views.vehicle_create, name='vehicle_create'),
    
    path('service_record_create/', views.service_record_create, name='service_record_create'),
    path('service_invoice_create/', views.service_invoice_create, name='service_invoice_create'),

    path("login/",views.login.as_view(),name="login"),
	path("logout/", views.logout, name="logout"),
    
    path("",views.index,name="index"),
    path("inventory/",views.inventory,name="inventory"),
    path("customers/",views.customers,name="customers"),       

    path("employee/",views.employee,name="employee"), 
    path('employee/delete/<int:pk>/', views.employee_delete, name='employee_delete'),      
    path('customer/delete/<int:pk>/', views.customer_delete, name='customer_delete'),
    path('vehicle/delete/<int:pk>/', views.vehicle_delete, name='vehicle_delete'),
    path('spare_part/delete/<int:pk>/', views.spare_part_delete, name='spare_part_delete'),
    path('inventory_invoice/delete/<int:pk>/', views.inventory_invoice_delete, name='inventory_invoice_delete'),
    path('service/delete/<int:pk>/', views.service_delete, name='service_delete'),
    path('service_invoice/cancel/<int:pk>/', views.service_invoice_cancel, name='service_invoice_cancel'),
    path('service/status/<int:pk>/', views.service_status_update, name='service_status_update'),
    path('service_invoice/status/<int:pk>/', views.service_invoice_status_update, name='service_invoice_status_update'),
    
    path("profile/",views.profile,name="profile"),       
    path("services/",views.services,name="services"),       
]

VSC_ERP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Masters/',include('Masters.urls')),
    path('chaining/', include('smart_selects.urls')),

    path('',include('CORE.urls')),
]

templates/partials/components/content_navbar.html
{% load static %}

<nav class="navbar navbar-expand bg-white shadow mb-4 topbar">
    <div class="container-fluid"><button class="btn btn-link d-md-none me-3 rounded-circle" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
        <form class="d-none d-sm-inline-block mw-100 ms-md-3 me-auto my-2 my-md-0 navbar-search">
            <div class="input-group"><input class="bg-light form-control border-0 small" type="text" placeholder="Search for ..."><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
        </form>
        <ul class="navbar-nav flex-nowrap ms-auto">
            <li class="nav-item dropdown show d-sm-none no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="true" data-bs-toggle="dropdown" href="#"><i class="fas fa-search"></i></a>
                <div class="dropdown-menu show p-3 dropdown-menu-end animated--grow-in" data-bs-popper="none" aria-labelledby="searchDropdown">
                    <form class="w-100 me-auto navbar-search">
                        <div class="input-group"><input class="bg-light border-0 form-control small" type="text" placeholder="Search for ..."><button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button></div>
                    </form>
                </div>
            </li>
            <div class="d-none d-sm-block topbar-divider"></div>
            <li class="nav-item dropdown no-arrow">
                <div class="nav-item dropdown no-arrow">
                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#">
                        <span class="d-none d-lg-inline me-2 text-gray-600 small">{{ user.username }}</span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
                            <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
                        </svg>
                    </a>

                    <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in">
                        <a class="dropdown-item" href="{% url 'CORE:profile' %}">
                            <i class="fas fa-user me-2 fa-sm fa-fw text-gray-400"></i>&nbsp;Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs me-2 fa-sm fa-fw text-gray-400"></i>&nbsp;Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list me-2 fa-sm fa-fw text-gray-400"></i>&nbsp;Activity log
                        </a>
                        
                        <div class="dropdown-divider"></div>

                        <form action="/logout/" method="post" class="my-1">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item">
                                <i class="fas fa-sign-out-alt me-2 fa-sm fa-fw text-gray-400"></i>&nbsp;Logout
                            </button>
                        </form>

                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/partials/components/footer.html
{% load static %}
<footer class="bg-white sticky-footer">
    <div class="container my-auto">
        <div class="text-center my-auto copyright"><span>Copyright © VSC ERP 2025</span></div>
    </div>
</footer>

templates/partials/components/navbar.html
{% load static %}
<nav class="navbar align-items-start p-0 sidebar sidebar-dark accordion bg-gradient-primary navbar-dark" style="background: rgb(43,50,72);">
    <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center m-0 sidebar-brand" href="{% url 'CORE:index' %}">
            <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-shuttle-van"></i></div>
            <div class="mx-3 sidebar-brand-text"><span>VSC ERP</span></div>
        </a>
        <hr class="my-0 sidebar-divider">
        <ul class="navbar-nav text-light" id="accordionSidebar">
            <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'CORE:index' %}"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a></li>
            <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'profile' %}active{% endif %}" href="{% url 'CORE:profile' %}"><i class="fas fa-user"></i><span>Profile</span></a></li>
            <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'inventory' %}active{% endif %}" href="{% url 'CORE:inventory' %}"><i class="fas fa-table"></i><span>Inventory</span></a></li>
            <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'services' %}active{% endif %}" href="{% url 'CORE:services' %}"><i class="fas fa-table"></i><span>Services</span></a></li>
            <li class="nav-item"><a class="nav-link {% if request.resolver_match.url_name == 'customers' %}active{% endif %}" href="{% url 'CORE:customers' %}"><i class="fas fa-table"></i><span>Customers</span></a></li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'employee' %}active{% endif %}" href="{% url 'CORE:employee' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person-fill">
                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"></path>
                    </svg>
                    <span>Employee</span>
                </a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16">
  <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z"/>
  <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"/>
</svg><span>Admin Dashboard</span></a></li>

        </ul>
        <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
    </div>
</nav>

templates/partials/components/toast_container.html
<div class="toast-container">
    {% for message in messages %}
        <div id="toast-1" class="toast fade text-bg-{{ message.tags }} position-fixed bottom-0 end-0 me-2 mb-2" role="alert" style="display: block;">
            <div class="toast-body" role="alert">
                <div class="row">
                    <div class="col">
                        <p>{{ message }}</p>
                    </div>
                    <div class="col-auto text-end align-self-start"><button class="btn-close btn-close-white ms-2 mb-1 close" type="button" aria-label="Close" data-bs-dismiss="toast"></button></div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
 
<script>
    const toastElList = document.querySelectorAll('.toast')
    const toastList = [...toastElList].map(toastEl => new bootstrap.Toast(toastEl,{
        'delay':5000,
        'autohide':true
    }))
    toastList.forEach(toast => toast.show());
</script>